#cloud-config
write_files:
# files for supervisor
  - path: ${supervisor_service_file_destination}
    content: ${base64encode(supervisor_service_file_contents)}
    encoding: b64
    owner: ${username}:${username}

# files for conductor
  - path: ${conductor_service_file_destination}
    content: ${base64encode(conductor_service_file_contents)}
    encoding: b64
    owner: ${username}:${username}
%{ if license_file_contents != "" }
  - path: /data/rama/license/rama.license
    content: ${base64encode(license_file_contents)}
    encoding: b64
    owner: ${username}:${username}
%{ endif }
